version: '2.1'
orbs:
  node: circleci/node@5.0.2
  #heroku: circleci/heroku@1.2.6
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run: npm run test
jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.16.1'
      - run: node --version

  build_and_test:
    executor: node/default
    steps:
      - checkout
      - run: node --version
      - run: sudo npm install -g npm@latest gatsby-cli gh-pages
      - node/install-packages:
          cache-path: ~/project/node_modules
          pkg-manager: yarn
      - run:
          command: gatsby build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy: # this can be any name you choose
    executor: node/default
#    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - run: ls -alh ~/project
#      - heroku/deploy-via-git:
#          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  test_my_app:
    jobs:
      - install-node-example
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
